### PR TITLE
Allow IDE assistance

### PR DESCRIPTION
**Pull request by dadeo**
I have added types to fields/variables/params to allow assistance and easier navigation from an IDE.  Also, The @ClosureParams allows the IDE to assist within a Closure.

### CODE REVIEW

**Comment by benkiefer** [comment]
@greathouse @dadeo is working with us on mercury, and it would be a huge help to have auto-complete from intellij, especially for new devs. Thank you!

**Comment by greathouse** [comment]
This should now be released as version 1.0.10.

**Comment by benkiefer** [comment]
Thank you!

**Comment by dadeo** [comment]
Thanks!

**Pull request merged**
